# Generated by Django 4.1.9 on 2023-05-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_password'),
        ('Projects', '0001_initial'),
        ('Organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orgnisation',
            new_name='Organisations',
        ),
    ]
